version: "2"
services:
    node9:
        image: "node:9"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/home/node/app
        ports:
            - "8089:1337"
        command: "npm start"
    node8:
        image: "node:8"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/home/node/app
        ports:
            - "8088:1337"
        command: "npm start"
    node6:
        image: "node:6"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/home/node/app
        ports:
            - "8086:1337"
        command: "npm start"

    node_alpine:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-alpine
        volumes:
            - ./:/app/
        ports:
            - "3000:3000"

    node_7_alpine:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-7-alpine
        volumes:
            - ./:/app/
        ports:
            - "3007:3000"

    node_6_alpine:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-6-alpine
        volumes:
            - ./:/app/
        ports:
            - "3006:3000"
