version: '3'
services:
    express:
        environment:
            - DBWEBB_DSN=mongodb://mongodb:27017/movie
        links:
            - mongodb
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - ./:/app/
            - /app/node_modules/
        ports:
            - 1337:1337
        command: "npm start"

    mongodb:
        image: mongo
        container_name: "mongodb1"
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data2/db:/data2/db
        ports:
            - 27017:27017
        command: mongod
